### ISSUE TITLE
error function "std::atomic<unsigned long long>::operator=(const std::atomic<unsigned long long> &)" cannot be referenced -- it is a deleted function

### ISSUE THREAD

**Issue by chrisdane** [r-spatial/s2#127]
Hi

When I try to install the s2 package, I get the following error: 
```r
R.version
#platform       x86_64-pc-linux-gnu         
#svn rev        80317                                   
#version.string R version 4.1.0 (2021-05-18)
install.packages("s2") 
Installing package into ‘~/scripts/r/packages/bin/r_4.1’
(as ‘lib’ is unspecified)                                                                                                                            
trying URL 'https://cloud.r-project.org/src/contrib/s2_1.0.5.tar.gz'
Content type 'application/x-gzip' length 1605805 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘s2’ ...
** package ‘s2’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Testing compiler using PKG_CFLAGS= 
Using PKG_LIBS=-lssl -lcrypto  
Using PKG_CFLAGS=  -DIS_LITTLE_ENDIAN
** libs
icpc -std=gnu++11 -I"/path/to/r/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c cpp-compat.cpp -o cpp-compat.o
...
/usr/include/c++/4.8.5/bits/stl_algobase.h(739): error: function "std::atomic<unsigned long long>::operator=(const std::atomic<unsigned long long> &)" (declared at line 697 of "/usr/include/c++/4.8.5/atomic") cannot be referenced -- it is a deleted function
        *__first = __value;
                 ^
          detected during:
            instantiation of "__gnu_cxx::__enable_if<<expression>, _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp &) [with _OutputIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 786
            instantiation of "_OI std::fill_n(_OI, _Size, const _Tp &) [with _OI=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 515 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}]" at line 544 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}]" at line 605 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp> &) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 1225 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}) [with _Tp=std::atomic<unsigned long long>, _Alloc=std::allocator<std::atomic<unsigned long long>>]" at line 271 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}, const std::vector<_Tp, _Alloc>::allocator_type &) [with _Tp=std::atomic<unsigned long long>, _Alloc=std::allocator<std::atomic<unsigned long long>>]" at line 132 of "s2/encoded_s2shape_index.cc"

compilation aborted for s2/encoded_s2shape_index.cc (code 2)
make: *** [/path/to/r/lib64/R/etc/Makeconf:175: s2/encoded_s2shape_index.o] Error 2
ERROR: compilation failed for package ‘s2’
* removing ‘~/scripts/r/packages/bin/r_4.1/s2’

The downloaded source packages are in
        ‘/work/tmp/Rtmp8MEHEm/downloaded_packages’
Warning message:
In install.packages("s2") :
  installation of package ‘s2’ had non-zero exit status
```

Thanks a lot for any help and kind regards,
Chris

**Comment by paleolimbot** [comment]
I will have to ask about the specific error since this is outside my expertise, but it looks like you're using the intel C++ compiler instead of gcc. If you know how to use gcc on your system you may have to  do so to install s2 for now.

**Comment by chrisdane** [comment]
Ok. Sorry I am no expert in these things.

```bash
which R
# /path/to/r
R CMD config CC
# icc -std=gnu99
icc -v
# icc version 19.1.2.254 (gcc version 6.1.0 compatibility)
strings -a /path/to/r/bin/exec/R | grep CC:
# GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-28)
```
I am on a supercomputer where software is loaded via `module`s. In case of the error in my initial post, these modules were loaded:
```bash
module purge
module load R/4.1.0 intel.compiler/19.1.2
```
When I additionally load
```bash
module load gcc/6.1.0(default)
```
(no other gcc version available via `module`) and rerun the installation, another error occurs:
```r
install.packages("s2")
...
Found pkg-config cflags and libs!
Testing compiler using PKG_CFLAGS= 
Using PKG_LIBS=-lssl -lcrypto  
Using PKG_CFLAGS=  -DIS_LITTLE_ENDIAN
** libs
icpc -std=gnu++11 -I"/path/to/r/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c cpp-compat.cpp -o cpp-compat.o
...
icpc -std=gnu++11 -I"/path/to/r/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c s2/s2min_distance_targets.cc -o s2/s2min_distance_targets.o

Error: A license for Comp-CL is not available (-13,128).

License file(s) used were (in this order):
**  1.  /global/opt/intel/licenses/USE_SERVER.lic
**  2.  /global/opt/intel/licenses/l_FH75DJGJ.lic
**  3.  /global/AWIsoft/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/../../Licenses
**  4.  ~/Licenses
**  5.  ~/intel/licenses
**  6.  /Users/Shared/Library/Application Support/Intel/Licenses
**  7.  /global/AWIsoft/intel/2020/compilers_and_libraries_2020.2.254/linux/bin/intel64/*.lic

Please refer http://software.intel.com/sites/support/ for more information..

icpc: error #10052: could not checkout FLEXlm license
make: *** [/path/to/r/lib64/R/etc/Makeconf:175: s2/s2min_distance_targets.o] Error 1
ERROR: compilation failed for package ‘s2’
```
How can I tell r to use another compiler for installing packages? From what I understand, the same compiler needs to be used as was used for the installation of r itself? Is it icc or gcc in my case?

Thanks a lot for help!

**Comment by edzer** [comment]
This still seems to call the `icpc` compiler, not gcc. I think your problem is with selecting, installing and using the software on your supercomputer, and you should look for support at the IT people managing this computer, your problems are not with this package.

**Comment by paleolimbot** [comment]
You can try `withr::with_makevars(list(CXX11 = "g++"), install.packages("s2")`, since the supercomputer settings are likely out of your control (if they aren't, icc is a largely untested choice to use with R packages). If you need to change other values, you can check what R is seeing like this:

``` r
withr::with_makevars(list(CXX11 = "g++"), system("R CMD config CXX11"))
#> [1] 0
```

I'm going to look into whether or not icc is common enough that we need to worry about supporting it here (it's certainly no less valid than making sure s2 works on Solaris).

**Comment by paleolimbot** [comment]
Another thing you could try is `withr::with_makevars(list(CXX11STD = "-std=c++11"), install.packages("s2")` (you're looking to get `icpc -std=gnu++11` changed to `icpc -std=c++11` since your supercomputer's version of gcc is rather old).

I'd love to know the results of your testing as we have no other way to test for the intel C++ compiler!

**Comment by chrisdane** [comment]
Hi

Thanks a lot for the suggestions @paleolimbot!

The first command yields this error with both `module list: 1) R/4.1.0   2) intel.compiler/19.1.2   3) gcc/6.1.0(default)` or `module list: 1) R/4.1.0   2) intel.compiler/19.1.2`:
```r
withr::with_makevars(list(CXX11 = "g++"), install.packages("s2"))
Found pkg-config cflags and libs!
Testing compiler using PKG_CFLAGS= 
Using PKG_LIBS=-lssl -lcrypto  
Using PKG_CFLAGS=  -DIS_LITTLE_ENDIAN
** libs
g++ -std=gnu++11 -I"/path/to/r/4.1.0_intel19.1.2/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/4.1.0_intel19.1.2/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c cpp-compat.cpp -o cpp-compat.o
g++: error: language Host not recognized
g++: error: language Host not recognized
make: *** [/path/to/r/4.1.0_intel19.1.2/lib64/R/etc/Makeconf:177: cpp-compat.o] Error 1
ERROR: compilation failed for package ‘s2’
```

The second command works with `module list: 1) R/4.1.0   2) intel.compiler/19.1.2   3) gcc/6.1.0(default)`:
```r
withr::with_makevars(list(CXX11STD = "-std=c++11"), install.packages("s2"))
Found pkg-config cflags and libs!
Testing compiler using PKG_CFLAGS= 
Using PKG_LIBS=-lssl -lcrypto  
Using PKG_CFLAGS=  -DIS_LITTLE_ENDIAN
** libs
icpc -std=c++11 -I"/path/to/r/4.1.0_intel19.1.2/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/4.1.0_intel19.1.2/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c cpp-compat.cpp -o cpp-compat.o
...
* DONE (s2)
library(s2)
```

but not with  `module list: 1) R/4.1.0   2) intel.compiler/19.1.2` only (same error as in initial post):
```r
withr::with_makevars(list(CXX11STD = "-std=c++11"), install.packages("s2"))
Found pkg-config cflags and libs!
Testing compiler using PKG_CFLAGS= 
Using PKG_LIBS=-lssl -lcrypto  
Using PKG_CFLAGS=  -DIS_LITTLE_ENDIAN
** libs
icpc -std=c++11 -I"/path/to/r/4.1.0_intel19.1.2/lib64/R/include" -DNDEBUG -I../inst/include -I'/path/to/r/4.1.0_intel19.1.2/lib64/R/library/Rcpp/include' -I'~/scripts/r/packages/bin/r_4.1/wk/include' -I/usr/local/include  -DIS_LITTLE_ENDIAN -pthread -fpic  -O2 -fpic -xHost  -c cpp-compat.cpp -o cpp-compat.o
...
/usr/include/c++/4.8.5/bits/stl_algobase.h(739): error: function "std::atomic<unsigned long long>::operator=(const std::atomic<unsigned long long> &)" (declared at line 697 of "/usr/include/c++/4.8.5/atomic") cannot be referenced -- it is a deleted function
        *__first = __value;
                 ^
          detected during:
            instantiation of "__gnu_cxx::__enable_if<<expression>, _OutputIterator>::__type std::__fill_n_a(_OutputIterator, _Size, const _Tp &) [with _OutputIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 786
            instantiation of "_OI std::fill_n(_OI, _Size, const _Tp &) [with _OI=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 515 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}]" at line 544 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}]" at line 605 of "/usr/include/c++/4.8.5/bits/stl_uninitialized.h"
            instantiation of "void std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp> &) [with _ForwardIterator=std::atomic<unsigned long long> *, _Size=std::size_t={unsigned long}, _Tp=std::atomic<unsigned long long>]" at line 1225 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}) [with _Tp=std::atomic<unsigned long long>, _Alloc=std::allocator<std::atomic<unsigned long long>>]" at line 271 of "/usr/include/c++/4.8.5/bits/stl_vector.h"
            instantiation of "std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type={std::size_t={unsigned long}}, const std::vector<_Tp, _Alloc>::allocator_type &) [with _Tp=std::atomic<unsigned long long>, _Alloc=std::allocator<std::atomic<unsigned long long>>]" at line 132 of "s2/encoded_s2shape_index.cc"

compilation aborted for s2/encoded_s2shape_index.cc (code 2)
make: *** [/path/to/r/4.1.0_intel19.1.2/lib64/R/etc/Makeconf:175: s2/encoded_s2shape_index.o] Error 2
ERROR: compilation failed for package ‘s2’
```

The 2nd command works, although `icpc` is used for compilation. Does that make sense @paleolimbot?

@edzer: You are right, this is is rather an issue for the system-op. However, if the `s2` package was not tested with the intel compiler, shouldnt there be a warning at the start of the installation? At least, this is what I would like to see as a user. 

Cheers,
Chris

**Comment by paleolimbot** [comment]
I'm glad the second command worked!

Edzer is right that this a system admin issue...you have an invalid system setup (out of your control) that will fail to install any package that requires C++11 (which is a lot of them). If you have the ability to do so, you should let your system admin know this (they should update their default R Makevars to use `-std=c++11`  and load a `gcc` version that supports C++11 when loading the R module). Your setup is in the category of "very strange", which I'm happy to help with, but we can't do much to improve the install warning.

**Comment by edzer** [comment]
> However, if the s2 package was not tested with the intel compiler, shouldnt there be a warning at the start of the installation? At least, this is what I would like to see as a user.

Why would we help users of a compiler that nearly nobody has access to? The platform & compiler combinations we routinely check against are found here: https://cran.r-project.org/web/checks/check_results_s2.html

**Comment by chrisdane** [comment]
Thanks both of you for this valuable insight!

**Comment by paleolimbot** [comment]
The argument for continuing to check on Solaris is, I believe, that it is able to catch errors that would otherwise have gone undetected (it certainly has for some of my compiled code). I think that applies here. I also checked with the r-lib team and they have updated several of their packages to ensure that they compile on `icc` without error.

**Comment by chrisdane** [comment]
Sorry for the spam, but can you explain why
```bash
R CMD config CC
# icc -std=gnu99
```
but
```bash
strings -a /path/to/r/4.1.0_intel19.1.2/lib64/R/bin/exec/R | grep CC:
# GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-28)
readelf -p .comment /path/to/r/4.1.0_intel19.1.2/lib64/R/bin/exec/R
#  [     0]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-28)
objdump -s --section .comment /path/to/r/4.1.0_intel19.1.2/lib64/R/bin/exec/R | grep CC:
# 0000 4743433a 2028474e 55292034 2e382e35  GCC: (GNU) 4.8.5
```
i.e. everything points to gcc as the compiler and not icc?

Thanks a lot for the education!

**Comment by paleolimbot** [comment]
This is outside my expertise...it looks as though your copy of R was compiled with icc and might be using the gcc standard library? GCC 4.8 is many years old and it's odd that it's used at all for a newly released version of R.

**Comment by paleolimbot** [comment]
Also, the compiler used for packages, while it should be the same as that used to compile R, is totally configurable via various `Makevars` files. It's generally discouraged to  mix and match compilers between R packages and the compiler used to build R, but it happens all the time and usually works.

**Comment by chrisdane** [comment]
Thanks!
