### ISSUE TITLE
New s2 version fails to compile on old Windows + R 3.6

### ISSUE THREAD

**Issue by paleolimbot** [r-spatial/s2#140]
```
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/include" -DNDEBUG -DS2_USE_EXACTFLOAT -D_USE_MATH_DEFINES -DNDEBUG -DIS_LITTLE_ENDIAN -I../windows/openssl-1.1.1k/include -I../src -I"D:/a/_temp/Library/Rcpp/include" -I"D:/a/_temp/Library/wk/include"        -O2 -Wall  -mtune=core2 -Wall -pedantic -c absl/time/internal/cctz/src/time_zone_format.cc -o absl/time/internal/cctz/src/time_zone_format.o
In file included from absl/time/internal/cctz/src/time_zone_format.cc:27:0:
../src/absl/base/config.h:297:1: warning: multi-line comment [-Wcomment]
 // #if (defined(__clang__) && !defined(_WIN32)) || \
 ^
absl/time/internal/cctz/src/time_zone_format.cc: In function 'char* absl::lts_20210324::time_internal::cctz::detail::{anonymous}::strptime(const char*, const char*, tm*)':
absl/time/internal/cctz/src/time_zone_format.cc:63:12: error: 'get_time' is not a member of 'std'
   input >> std::get_time(tm, fmt);
            ^
```

**Comment by paleolimbot** [comment]
Fixed in #142
